parser: babel-eslint
extends: airbnb
env:
  node: true
  jasmine: true
rules:
  # no need force jsx
  react/jsx-filename-extension:
    - 1
    - extensions: [.js, .jsx]

  # will fix in future
  jsx-a11y/html-has-lang: 0
  react/forbid-prop-types: 0

globals:
  fetch: true
